language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t nikhilgb/docker-react -f Dockerfile.dev .

script:
  - docker run nikhilgb/docker-react npm run test -- --coverage
