language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t nikhilgb/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nikhilgb/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-069653090426"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_key_id:
    secure: $AWS_SECRET_KEY
